### ISSUE TITLE
Korean specific options and KoGPT(HF) tokenizer 

### ISSUE THREAD

**Issue by haven-jeon** [SKT-LSL/Megatron-LM#1]
Azure DevOps 개발 브랜치 가져오며  관련 이슈 생성합니다. 

- 한국어 대응 https://github.com/hyunwoongko/kss 모듈 적용
- 전처리시 EOS 토큰 추가
- hugingface tokenizer 인터페이스 추가

**Comment by haven-jeon** [comment]
https://github.com/SKT-LSL/Megatron-LM/tree/feature/kogpt_preprocess_data

**Comment by oceanos74** [comment]
@haven-jeon @bage79 전처리에서 모듈에서 개발하고 있는 한국어 tokenizer 와 관계는 어떻게 되나요?

**Comment by haven-jeon** [comment]
> 
> 
> @haven-jeon @bage79 전처리에서 모듈에서 개발하고 있는 한국어 tokenizer 와 관계는 어떻게 되나요?

전처리 모듈에서 개발해주신 토크나이저를 적용하기 위한 코드입니다.
